name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test
    
    - name: Validate main HTML files
      run: |
        if [ -f "index.html" ]; then
          echo "✅ index.html found"
        else
          echo "❌ index.html not found"
          exit 1
        fi
    
    - name: Check CSS files
      run: |
        if [ -f "styles.css" ] || [ -f "css/styles.css" ]; then
          echo "✅ CSS files found"
        else
          echo "❌ CSS files not found"
          exit 1
        fi
    
    - name: Check JS files
      run: |
        if [ -f "script.js" ] || [ -f "js/main.js" ]; then
          echo "✅ JS files found"
        else
          echo "❌ JS files not found"
          exit 1
        fi
    
    - name: Build project
      run: npm run build